---

- name: Ensure group "docker"
  ansible.builtin.group:
    name: docker
    state: present
    gid: 999
  become: true

- name: "Ensure {{ docker_user }} in docker group"
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  become: true
